### ISSUE TITLE
[Bug]: MythicMobs Compatibility Issue - Easy Fix

### ISSUE THREAD

**Issue by ShermansWorld** [Errored-Innovations/HeadsPlus#106]
### Checklist

- [X] Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?
- [X] Have you checked to see if others have submitted the same bug report?
- [X] Have you been able to reproduce the bug more then once?

### Description of the bug

MythicMobs has recently changed the name of its classes in one of its new versions and its been screwing over a bunch of plugins that hook into it. I've experienced this problem myself with one of my own plugins. To fix this bug you need to update your MythicMobs imports (or have an option to disable the hooks altogether, depending on if they've changed anything that you're using). You can see an example of the  "NoClassDefFoundError" below when HeadsPlus tries to hook into MythicMobs. This one is on the PlayerDeathEvent but I believe it was also throwing and error for EntityDeathEvent. 

- [Mon 17:52:15 ERROR Minecraft] Could not pass event PlayerDeathEvent to HeadsPlus v7.0.0-MVP-1
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
    at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.util.HPUtils.isMythicMob(HPUtils.java:132)
    at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.listeners.PlayerDeathListener.onEvent(PlayerDeathListener.java:54)
    at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.listeners.PlayerDeathListener.onEvent(PlayerDeathListener.java:26)
    at HeadsPlus-7.0.0-MVP-1.jar//io.github.thatsmusic99.headsplus.util.events.HeadsPlusEventExecutor.execute(HeadsPlusEventExecutor.java:37)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
    at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:906)
    at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:862)
    at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1449)
    at net.minecraft.world.entity.player.Player.hurt(Player.java:922)
    at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1027)
    at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:1894)
    at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1708)
    at net.minecraft.world.level.block.Block.fallOn(Block.java:458)
    at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1519)
    at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:366)
    at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1456)

### Steps To Reproduce

1: Run the latest version of HeadsPlus and MythicMobs 5.0.x on a 1.18.x server 
2: Have custom mobs configured
3: Errors generated on PlayerDeathEvent and EntityDeathEvent

Fix: Update MythicMobs imports

**Comment by Thatsmusic99** [comment]
Well, uh, you almost got me there, but you're not running the latest version of HeadsPlus. And if anything, I did fix that in one of the later versions. For reference, you are running 7.0.0-MVP-1, 7.0.6 is available on SpigotMC and 7.0.7 has dev builds available.

Feel free to re-open the issue if it turns out they've updated everything again, and if I have to stare down the devs again as a result.

**Comment by ShermansWorld** [comment]
Ahh my bad. I thought I was running a later version. I'll try out a dev build now, thank you. Also I'll repost if they change the MythicsMobs source again because I work with it quite a bit.
