### ISSUE TITLE
[Bug]: Im getting this error when I change in config.yml from "player-drops: true" to "player-drops: false"

### ISSUE THREAD

**Issue by AntonyMax** [Errored-Innovations/HeadsPlus#114]
### Checklist

- [X] Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?
- [X] Have you checked to see if others have submitted the same bug report?
- [X] Have you been able to reproduce the bug more then once?

### Description of the bug

Im getting this error everytime while start the server after edit the config file.
pls help to clear this error

### Steps To Reproduce

[10:18:58 WARN]: java.lang.NullPointerException: Cannot invoke "io.github.thatsmusic99.configurationmaster.api.ConfigSection.getKeys(boolean)" because the return value of "io.github.thatsmusic99.headsplus.config.ConfigMobs.getConfigSection(String)" is null
[10:18:58 WARN]: at HeadsPlus-7.0.16.jar//io.github.thatsmusic99.headsplus.managers.EntityDataManager.setupHeads(EntityDataManager.java:218)
[10:18:58 WARN]: at HeadsPlus-7.0.16.jar//io.github.thatsmusic99.headsplus.managers.EntityDataManager.access$100(EntityDataManager.java:18)
[10:18:58 WARN]: at HeadsPlus-7.0.16.jar//io.github.thatsmusic99.headsplus.managers.EntityDataManager$1.run(EntityDataManager.java:50)
[10:18:58 WARN]: at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[10:18:58 WARN]: at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:18:58 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:18:58 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[10:18:58 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[10:18:58 WARN]: at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by AntonyMax** [comment]
Now only found that, Im getting this error when I change in config.tml from "player-drops: true" to "player-drops: false".
pls help to clear this error.

**Comment by Thatsmusic99** [comment]
This was already fixed in https://ci.pluginwiki.us/job/HeadsPlus/148/

**Comment by AntonyMax** [comment]
thnx for the help,
But i have a doubt, then why didn't update this in spigotmc.org ?

**Comment by Thatsmusic99** [comment]
No worries! I've been quite busy as of recent with other things going on, so it hasn't been on my mind to update the plugin - however I did want another update done with some other additions/fixes, so when that's done, the plugin'll get an update
