### ISSUE TITLE
[Bug]: Failed to add to statistics total

### ISSUE THREAD

**Issue by Kismalax** [Errored-Innovations/HeadsPlus#120]
### Checklist

- [X] Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?
- [X] Have you checked to see if others have submitted the same bug report?
- [X] Have you been able to reproduce the bug more then once?

### Description of the bug

After updating from 7.1.1 to 7.1.5, I get this error every time someone obtains a head:

```
[HeadsPlus] Failed to add to statistics total HUNTING, metadata entity=ZOMBIFIED_PIGLIN, head HP#zombified_piglin and user 70ddcd39-3ea9-3e95-a6b9-d10c266d2e6c - an internal error occurred. Please report the below stacktrace and error to the developer.
java.sql.SQLException: Operation not allowed after ResultSet closed
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
       at com.mysql.cj.jdbc.result.ResultSetImpl.checkClosed(ResultSetImpl.java:485)
       at com.mysql.cj.jdbc.result.ResultSetImpl.next(ResultSetImpl.java:1802)
       at HeadsPlus-7.1.5.jar//io.github.thatsmusic99.headsplus.sql.StatisticsSQLManager.lambda$addToTotal$9(StatisticsSQLManager.java:313)
       at HeadsPlus-7.1.5.jar//io.github.thatsmusic99.headsplus.sql.SQLManager.lambda$createConnection$1(SQLManager.java:87)
       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
       at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
       at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
       at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:840)
```

The player's statistics will not increase in this case.

### Steps To Reproduce

Update from 7.1.1 to 7.1.5, then kill some mobs.

### Additional Information

```shell
Im still on Paper 1.20.2.
```

**Comment by Thatsmusic99** [comment]
This should be resolved in the dev builds: https://ci.pluginwiki.us/job/HeadsPlus/180/

**Comment by Kismalax** [comment]
I have the same issue with the last build.
I'm using mysql database. Sorry, I didn't mention it in the original post.
```
[HeadsPlus] Failed to add to statistics total HUNTING, metadata entity=ZOMBIFIED_PIGLIN, head HP#zombified_piglin and user 70ddcd39-3ea9-3e95-a6b9-d10c266d2e6c - an internal error occurred. Please report the below stacktrace and error to the developer.
java.sql.SQLException: Operation not allowed after ResultSet closed
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
       at com.mysql.cj.jdbc.result.ResultSetImpl.checkClosed(ResultSetImpl.java:485)
       at com.mysql.cj.jdbc.result.ResultSetImpl.next(ResultSetImpl.java:1802)
       at HeadsPlus-7.1.5-180.jar//io.github.thatsmusic99.headsplus.sql.StatisticsSQLManager.lambda$addToTotal$9(StatisticsSQLManager.java:316)
       at HeadsPlus-7.1.5-180.jar//io.github.thatsmusic99.headsplus.sql.SQLManager.lambda$createConnection$1(SQLManager.java:87)
       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
       at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
       at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
       at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
       at java.base/java.lang.Thread.run(Unknown Source)
```
