### ISSUE TITLE
[BUG] NPE from trying to open the favourites menu

### ISSUE THREAD

**Issue by Thatsmusic99** [Errored-Innovations/HeadsPlus#66]
Taken using the customheads.yml "extreme" dataset:

```
[13:23:09 WARN]: [HeadsPlus] Plugin HeadsPlus v7.0.0-BETA-1 generated an exception while executing task 137
java.lang.NullPointerException: Cannot invoke "io.github.thatsmusic99.headsplus.config.ConfigHeadsSelector$BuyableHeadInfo.forceBuildHead()" because the return value of "io.github.thatsmusic99.headsplus.config.ConfigHeadsSelector.getBuyableHead(String)" is null
        at io.github.thatsmusic99.headsplus.inventories.icons.content.CustomHead.<init>(CustomHead.java:32) ~[HeadsPlus-7.0.0-BETA-1.jar:?]
        at io.github.thatsmusic99.headsplus.inventories.list.HeadsFavourite.transformContents(HeadsFavourite.java:40) ~[HeadsPlus-7.0.0-BETA-1.jar:?]
        at io.github.thatsmusic99.headsplus.inventories.BaseInventory.lambda$new$1(BaseInventory.java:70) ~[HeadsPlus-7.0.0-BETA-1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-373]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-373]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-373]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by Thatsmusic99** [comment]
Fixed, sent a warning in console for when this occurs
