### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andy3559167** [Errored-Innovations/HeadsPlus#82]
- Server version: paper-1.18-66
- HeadsPlus version: 7.0.1
- Whether or not the plugin uses MySQL : NO
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: CMI
Error report when I type /heads(7.0.0-MVP-1 version can be used normally)
[06:42:23] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "io.github.thatsmusic99.configurationmaster.api.ConfigFile.getInteger(String)" because "this.hpi" is null
[06:42:23] [Server thread/WARN]: 	at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.BaseInventory.<init>(BaseInventory.java:60)
[06:42:23] [Server thread/WARN]: 	at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.list.HeadsMenu.<init>(HeadsMenu.java:17)
[06:42:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[06:42:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[06:42:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[06:42:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[06:42:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[06:42:23] [Server thread/WARN]: 	at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.InventoryManager$InventoryType.getInventory(InventoryManager.java:37)
[06:42:23] [Server thread/WARN]: 	at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.inventories.InventoryManager.open(InventoryManager.java:190)
[06:42:23] [Server thread/WARN]: 	at HeadsPlus-7.0.1.jar//io.github.thatsmusic99.headsplus.commands.Heads.onCommand(Heads.java:35)
[06:42:23] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:42:23] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:42:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[06:42:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[06:42:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Thatsmusic99** [comment]
This was fixed in #80 
Use https://ci.pluginwiki.us/job/HeadsPlus/47/artifact/target/HeadsPlus-7.0.1+DEV_47.jar

**Comment by andy3559167** [comment]
Interact > middle-click-head
Type: Boolean

Default Value: true

When this option is active, players can use their creative block pickup button on heads to have the head's texture applied to the new skull picked in their inventory.
Oh and I can’t find this option in config.

**Comment by andy3559167** [comment]
![image](https://user-images.githubusercontent.com/92452845/145653932-0b6df658-5ad3-42f3-a0cd-51b3212e1aee.png)
Also use /hp help the first line will display {default-pahed}.
