### ISSUE TITLE
[BUG] SQLITE_BUSY The database file is locked (database is locked)

### ISSUE THREAD

**Issue by TNTUP** [Errored-Innovations/HeadsPlus#86]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
State here when you have checked the following points above.

### Description of the bug
[0 02:42:37 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[0 02:42:37 WARN]:      at org.sqlite.core.DB.newSQLException(DB.java:1012)
[0 02:42:37 WARN]:      at org.sqlite.core.DB.newSQLException(DB.java:1024)
[0 02:42:37 WARN]:      at org.sqlite.core.DB.execute(DB.java:863)
[0 02:42:37 WARN]:      at org.sqlite.core.DB.executeUpdate(DB.java:904)
[0 02:42:37 WARN]:      at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[0 02:42:37 WARN]:      at HeadsPlus-7.0.2.jar//io.github.thatsmusic99.headsplus.sql.StatisticsSQLManager.addToTotalSync(StatisticsSQLManager.java:350)
[0 02:42:37 WARN]:      at HeadsPlus-7.0.2.jar//io.github.thatsmusic99.headsplus.sql.StatisticsSQLManager.lambda$addToTotal$9(StatisticsSQLManager.java:315)
[0 02:42:37 WARN]:      at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[0 02:42:37 WARN]:      at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[0 02:42:37 WARN]:      at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[0 02:42:37 WARN]:      at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[0 02:42:37 WARN]:      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[0 02:42:37 WARN]:      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[0 02:42:37 WARN]:      at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce
1. Can't tell how it happens, related to statistics
2. ...
3. ...

### Have you been able to reproduce the bug more than once?

Maybe, yes

### Expected behavior

No errors in console

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

Not any.
### Required information
- Server version: 1.17.1 
- HeadsPlus version: 7.0.2
- Whether or not the plugin uses MySQL SQLite
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: Yes
- Any other pieces of information that may be required.

## Additional information
Add any other information/notes you'd like to add at the bottom

**Comment by Thatsmusic99** [comment]
Nice to know this error is back to haunt me. Will get on this in hopefully the next hour.

**Comment by TNTUP** [comment]
> Nice to know this error is back to haunt me. Will get on this in hopefully the next hour.

Don't worry! You will squash them with your keyboard! *SMASH* boom fixed!

**Comment by Thatsmusic99** [comment]
Can I ask if this [dev build](https://ci.pluginwiki.us/job/HeadsPlus/51/) removes the errors at all? Feel free to have an ongoing report over the next 3 days or so

**Comment by TNTUP** [comment]
I'll try checking that out this night if theres no players on XD (I think it hates plugman, never tried it yet)

**Comment by TNTUP** [comment]
Looks like its still persisting :< 

onsole	: [0 15:07:40 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
Console	: [0 15:07:40 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1012)
Console	: [0 15:07:40 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1024)
Console	: [0 15:07:40 WARN]: 	at org.sqlite.core.DB.execute(DB.java:863)
Console	: [0 15:07:40 WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:904)
Console	: [0 15:07:40 WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
Console	: [0 15:07:40 WARN]: 	at HeadsPlus-7.0.3+DEV_51.jar//io.github.thatsmusic99.headsplus.sql.SQLManager.lambda$executeUpdate$0(SQLManager.java:81)
Console	: [0 15:07:40 WARN]: 	at HeadsPlus-7.0.3+DEV_51.jar//io.github.thatsmusic99.headsplus.sql.SQLManager.syncDatabaseOperation(SQLManager.java:87)
Console	: [0 15:07:40 WARN]: 	at HeadsPlus-7.0.3+DEV_51.jar//io.github.thatsmusic99.headsplus.sql.SQLManager.executeUpdate(SQLManager.java:80)
Console	: [0 15:07:40 WARN]: 	at HeadsPlus-7.0.3+DEV_51.jar//io.github.thatsmusic99.headsplus.sql.StatisticsSQLManager.addToTotalSync(StatisticsSQLManager.java:350)
Console	: [0 15:07:40 WARN]: 	at HeadsPlus-7.0.3+DEV_51.jar//io.github.thatsmusic99.headsplus.sql.StatisticsSQLManager.lambda$addToTotal$9(StatisticsSQLManager.java:315)
Console	: [0 15:07:40 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
Console	: [0 15:07:40 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
Console	: [0 15:07:40 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
Console	: [0 15:07:40 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
Console	: [0 15:07:40 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Console	: [0 15:07:40 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Console	: [0 15:07:40 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Thatsmusic99** [comment]
:( alright, will check it tomorrow, my dumbass waited 3 and a half hours for this zip file to upload just for it to get corrupted halfway through

**Comment by TNTUP** [comment]
> :( alright, will check it tomorrow, my dumbass waited 3 and a half hours for this zip file to upload just for it to get corrupted halfway through

Oh noes :( Take care and no rush, take your time! Also happy holidays!!

**Comment by Thatsmusic99** [comment]
Do you have a full log file for when this occurred (e.g. latest.log)? Happy holidays to you too!

**Comment by TNTUP** [comment]
> Do you have a full log file for when this occurred (e.g. latest.log)? Happy holidays to you too!

It happens sometimes, can't tell how to reproduce it. I did a quick check and its the same stacktrace as I posted above. I think this is harmless but can't tell if there's loss (statistics related?) 

Maybe better using MySQL? Maybe but that won't solve the issue for SQLite users =S

**Comment by Thatsmusic99** [comment]
There is definitely loss involved, some sort of connection isn't closing properly and that's causing the error, hence I asked for a full log file in case there's a reason why it happens.

**Comment by TNTUP** [comment]
[latest-thatsmusicIsAwesome.log](https://github.com/Errored-Innovations/HeadsPlus/files/7748006/latest-thatsmusicIsAwesome.log)

Here ya go ;)

**Comment by Thatsmusic99** [comment]
Ohhh boy, there's a lot I would've missed if I didn't get that, the error stays the same but the stacktrace differs occasionally which is the useful bit. Cheers!

**Comment by Thatsmusic99** [comment]
Appreciate the ego stretch btw

**Comment by TNTUP** [comment]
> Appreciate the ego stretch btw

xDDDD Damn I like your humor

**Comment by Thatsmusic99** [comment]
Another dev build went through for this, do you want to check for the errors with it? (https://ci.pluginwiki.us/job/HeadsPlus/54/artifact/target/HeadsPlus-7.0.3+DEV_54.jar)

**Comment by TNTUP** [comment]
> Another dev build went through for this, do you want to check for the errors with it? (https://ci.pluginwiki.us/job/HeadsPlus/54/artifact/target/HeadsPlus-7.0.3+DEV_54.jar)

Will try that on my next maintenance. Is it plugman-safe (?) although this isn't recommended

**Comment by Thatsmusic99** [comment]
Most likely no, quite frankly I wouldn't risk it

**Comment by TNTUP** [comment]
> Most likely no, quite frankly I wouldn't risk it

Okie dokie! I'll let you know when it happens (3 days span)

**Comment by TNTUP** [comment]
Still persists but it threw another error (this time it generated a report which I'll upload it here^^

Sqlite: https://paste.gg/p/anonymous/f3673f4819024a5eaf0018d01c73f533
[12.21.2021 07_08_22-REPORT-2.json.txt](https://github.com/Errored-Innovations/HeadsPlus/files/7758099/12.21.2021.07_08_22-REPORT-2.json.txt)

**Comment by Thatsmusic99** [comment]
Seems that you're still on dev build 51 according to the debug report, build 54 is meant to fix it 👀

**Comment by TNTUP** [comment]
> Seems that you're still on dev build 51 according to the debug report, build 54 is meant to fix it 👀

o_O I thought by putting the DEV54 jar would load first than DEV 51... Guess I'm the wrong x( Sorry!

**Comment by Thatsmusic99** [comment]
All good, I've seen a few people in my job do a similar thing so it's pretty normal to see that kind of thing happen.

**Comment by TNTUP** [comment]
Sadness :(

https://paste.gg/p/anonymous/a5c175418dae447db74dd056755ebf95

**Comment by Thatsmusic99** [comment]
That is quite annoying - do you think you can provide a full log of this again just to make sure nothing is missed?

**Comment by TNTUP** [comment]
> That is quite annoying - do you think you can provide a full log of this again just to make sure nothing is missed?

https://paste.gg/p/anonymous/fa86d53f7d3f4e23bbe3f6c4b0e99f29

**Comment by Thatsmusic99** [comment]
Looks like it's time to rewrite the entirety of SQL management in this plugin!

**Comment by TNTUP** [comment]
> Looks like it's time to rewrite the entirety of SQL management in this plugin!

Ouch. For now this can be ignored (the sqlite busy issue) until the end of Christmas/New Year. Take a break, profit your holidays with your family^^

**Comment by Thatsmusic99** [comment]
Wait no that's an overreaction, my mistake. I'll do that rewrite after the holidays if it's warranted 😂 trying one more thing.

**Comment by Thatsmusic99** [comment]
Tried one last thing [here](https://ci.pluginwiki.us/job/HeadsPlus/56/artifact/target/HeadsPlus-7.0.3+DEV_56.jar) as I noticed the error was happening in one specific place.

**Comment by TNTUP** [comment]
> Tried one last thing [here](https://ci.pluginwiki.us/job/HeadsPlus/56/artifact/target/HeadsPlus-7.0.3+DEV_56.jar) as I noticed the error was happening in one specific place.

Will test and report you back tomorrow or later^^

**Comment by TNTUP** [comment]
😭😭😭😭😭😭
[latestoof.log](https://github.com/Errored-Innovations/HeadsPlus/files/7765426/latestoof.log)

**Comment by Thatsmusic99** [comment]
this plugin really that stupid huh

man if only it could tell me WHY it's locked, I'll check it the next chance I get (most likely after Christmas but I can probably get it done tomorrow)

**Comment by TNTUP** [comment]
Okie dokie, for now I'll just discard those errors, statistics isn't very important in my case tho so thats fine :P (Else I can go with mysql if needed, could use it across all servers if I want)

Happy Holidays 👯

**Comment by Thatsmusic99** [comment]
It's that time again, I've rewritten the bulk of SQL which can be found [here](https://ci.pluginwiki.us/job/HeadsPlus/57/artifact/target/HeadsPlus-7.0.3+DEV_57.jar), let me know how that goes.

**Comment by TNTUP** [comment]
I'll let you know tomorrow, Github had issues this morning so I couldn't get it on time before sleeping or I forgot yesterday evening haha xD

**Comment by TNTUP** [comment]
Hey there 👋 

Today I haven't seen any HeadsPlus db errors! Yippie! For a first day, I'll give it 2 more days just to be sure its 100% solved. Else if you decide to close it, I'll let you know after 2 days :)

**Comment by TNTUP** [comment]
Heya @Thatsmusic99 been over 4 days and I hope you had a great holidays :) Sure I am, no more SQLITE errors !

**Comment by Thatsmusic99** [comment]
Brilliant news! I will do some cleaning up later for this update and release the new version with this fix as soon as possible.

**Comment by cloakfox** [comment]
> Brilliant news! I will do some cleaning up later for this update and release the new version with this fix as soon as possible.

I am just getting a few more of these kind of errors on current latest version of the plugin (7.1.5)
using paper 1.20.4
https://gist.github.com/cloakfox/22bb8406c3e80cfd748a75bcc2d17992

**Comment by Thatsmusic99** [comment]
I've tried improving some of the code surrounding adding statistics from what I've learned with similar errors from AT, can I ask if this helps at all? - https://ci.pluginwiki.us/job/HeadsPlus/174/

**Comment by cloakfox** [comment]
> I've tried improving some of the code surrounding adding statistics from what I've learned with similar errors from AT, can I ask if this helps at all? - https://ci.pluginwiki.us/job/HeadsPlus/174/

Hey, thanks for the quick response!

I've rebooted the server with the latest dev version and haven't seen any errors pop up so far (they where getting spammed before). It seems to be fixed! :tada:

**Comment by Thatsmusic99** [comment]
Awesome, I'll keep this open for another day or two just in case it reappears :)
