### ISSUE TITLE
The database file is locked 

### ISSUE THREAD

**Issue by FourNineRugz** [Errored-Innovations/HeadsPlus#98]
[17:22:44 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[17:22:44 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[17:22:44 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[17:22:44 WARN]:        at org.sqlite.core.DB.execute(DB.java:881)
[17:22:44 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:922)
[17:22:44 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[17:22:44 WARN]:        at HeadsPlus-7.0.5+DEV_78.jar//io.github.thatsmusic99.headsplus.sql.PlayerSQLManager.lambda$setXP$6(PlayerSQLManager.java:196)
[17:22:44 WARN]:        at HeadsPlus-7.0.5+DEV_78.jar//io.github.thatsmusic99.headsplus.sql.SQLManager.lambda$createConnection$1(SQLManager.java:82)
[17:22:44 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:22:44 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[17:22:44 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:22:44 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:22:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:22:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:22:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Thatsmusic99** [comment]
Fill out the issue template please.
